version: '3.3'
services:
    aspenselfcontained2:
        build:
          dockerfile: $ASPEN_DOCKER_2/dockerfile
        volumes:
            - '$ASPEN_CLONE_2:/usr/local/aspen-discovery'
            - '$ASPEN_DOCKER_2/site/:/usr/local/aspen-discovery/sites/test.localhostaspen'
            - '$ASPEN_DOCKER_2/etc/apache2/sites-enabled:/etc/apache2/sites-enabled'
            - '$ASPEN_DOCKER_2/data/aspen-discovery/test.localhostaspen:/data/aspen-discovery/test.localhostaspen'
            - '$ASPEN_DOCKER_2/var/log/aspen-discovery:/var/log/aspen-discovery'
            - '$ASPEN_DOCKER_2/site/conf/config.cron.ini:/etc/cron.d/test.localhostaspen'
        ports:
            - '8084:8080'
            - '8083:80'
        container_name: containeraspen2
        image: aspendocker2
        networks:
           external:

        tty: true


    mariadb:
        container_name: aspen-mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=aspen
            - MARIADB_DATABASE:aspen
            - MARIADB_USER:aspensuper
            - MARIADB_PASSWORD:aspensuper
            - MYSQL_TCP_PORT:7000
        image: 'mariadb:latest'
        volumes:
          - $ASPEN_DOCKER_2/setup.sql:/docker-entrypoint-initdb.d/init-script.sql
        networks:
          external:

networks:
   external:
        name: koha_kohanet
