version: '3.3'
services:
    aspenselfcontained2:
        build:
          dockerfile: $ASPEN_DOCKER/dockerfile
        volumes:
            - '$ASPEN_CLONE:/usr/local/aspen-discovery'
            - '$ASPEN_DOCKER/site/:/usr/local/aspen-discovery/sites/test.localhostaspen'
            - '$ASPEN_DOCKER/etc/apache2/sites-enabled:/etc/apache2/sites-enabled'
            - '$ASPEN_DOCKER/data/aspen-discovery/test.localhostaspen:/data/aspen-discovery/test.localhostaspen'
            - '$ASPEN_DOCKER/var/log/aspen-discovery:/var/log/aspen-discovery'
            - '$ASPEN_DOCKER/site/conf/crontab_settings.txt:/etc/cron.d/cron'
        ports:
            - '8084:8080'
            - '8083:80'
        container_name: containeraspen2
        image: aspendocker2
        networks:
           external:
        depends_on:
            mariadb:
                condition: service_healthy
        tty: true


    mariadb:
        container_name: aspen-mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=aspen
            - MARIADB_DATABASE:aspen
            - MARIADB_USER:aspensuper
            - MARIADB_PASSWORD:aspensuper
            - MYSQL_TCP_PORT:7000
        image: 'mariadb:latest'
        volumes:
          - $ASPEN_DOCKER/setup.sql:/docker-entrypoint-initdb.d/init-script.sql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-paspen", "-h", "localhost"]
            timeout: 20s
            retries: 10
        networks:
          external:

networks:
   external:
        name: koha_kohanet
